set_profile:
  name: "Setting profile"
  description: "Configure the profile for auto-mode."
  fields:
    device_id:
      name: "Device(s)"
      description: "Device(s) on which the command is to be executed."
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "ambrogio_robot"
          entity:
            domain: "device_tracker"
    profile:
      name: "Profile"
      description: "Select the profile you want to use."
      required: true
      example: 1
      default: 1
      selector:
        number:
          min: 1
          max: 3
          mode: box

work_now:
  name: "Mowing now"
  description: "Command the lawn mower to mow now."
  fields:
    device_id:
      name: "Device(s)"
      description: "Device(s) on which the command is to be executed."
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "ambrogio_robot"
          entity:
            domain: "device_tracker"
    area:
      name: "Zone"
      description: "Zone where the lawn mower should start."
      example: 1
      default: 1
      selector:
        number:
          min: 1
          max: 10
          mode: box

work_until:
  name: "Mowing until a certain time"
  description: "Command the lawn mower to mow until a certain time."
  fields:
    device_id:
      name: "Device(s)"
      description: "Device(s) on which the command is to be executed."
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "ambrogio_robot"
          entity:
            domain: "device_tracker"
    hours:
      name: "Hours"
      description: "Time until which lawn mower should drive in locale time and 24h format."
      required: true
      example: 12
      default: 12
      selector:
        number:
          min: 0
          max: 23
          step: 1
          mode: slider
    minutes:
      name: "Minutes"
      description: "Time until which lawn mower should drive in locale time and 24h format."
      required: true
      example: 30
      default: 0
      selector:
        number:
          min: 0
          max: 59
          step: 1
          mode: slider
    area:
      name: "Zone"
      description: "Zone where the lawn mower should start."
      example: 1
      default: 1
      selector:
        number:
          min: 1
          max: 10
          mode: box

border_cut:
  name: "Border cutting"
  description: "Command the lawn mower to cut the border."
  fields:
    device_id:
      name: "Device(s)"
      description: "Device(s) on which the command is to be executed."
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "ambrogio_robot"
          entity:
            domain: "device_tracker"

charge_now:
  name: "Charging now"
  description: "Command the lawn mower to charge now."
  fields:
    device_id:
      name: "Device(s)"
      description: "Device(s) on which the command is to be executed."
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "ambrogio_robot"
          entity:
            domain: "device_tracker"

charge_until:
  name: "Charging until a certain time"
  description: "Command the lawn mower to charge until a certain time."
  fields:
    device_id:
      name: "Device(s)"
      description: "Device(s) on which the command is to be executed."
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "ambrogio_robot"
          entity:
            domain: "device_tracker"
    hours:
      name: "Hours"
      description: "Time until which lawn mower should charge in locale time and 24h format."
      required: true
      example: 12
      default: 12
      selector:
        number:
          min: 0
          max: 23
          step: 1
          mode: slider
    minutes:
      name: "Minutes"
      description: "Time until which lawn mower should charge in locale time and 24h format."
      required: true
      example: 30
      default: 0
      selector:
        number:
          min: 0
          max: 59
          step: 1
          mode: slider
    weekday:
      name: "Day of week"
      description: "Numeric representation of the day of the week is 0 (for Sunday) through 6 (for Saturday)."
      required: true
      example: "1"
      default: "0"
      selector:
        select:
          options:
          - label: "Sunday"
            value: "0"
          - label: "Monday"
            value: "1"
          - label: "Tuesday"
            value: "2"
          - label: "Wednesday"
            value: "3"
          - label: "Thursday"
            value: "4"
          - label: "Friday"
            value: "5"
          - label: "Saturday"
            value: "6"

trace_position:
  name: "Tracing position"
  description: "Command the lawn mower to report its current position."
  fields:
    device_id:
      name: "Device(s)"
      description: "Device(s) on which the command is to be executed."
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "ambrogio_robot"
          entity:
            domain: "device_tracker"

keep_out:
  name: "Keep out of a location (no-go area)"
  description: "Commands the lawn mower to keep out of a location."
  fields:
    device_id:
      name: "Device(s)"
      description: "Device(s) on which the command is to be executed."
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "ambrogio_robot"
          entity:
            domain: "device_tracker"
    location:
      name: "Location"
      description: "Location from which the lawn mower should keep out."
      required: true
      example: 1
      default: 1
      selector:
        location:
          radius: true
    hours:
      name: "Hours"
      description: "Time until which lawn mower should keep out in locale time and 24h format."
      example: 12
      default: 12
      selector:
        number:
          min: 0
          max: 23
          step: 1
          mode: slider
    minutes:
      name: "Minutes"
      description: "Time until which lawn mower should keep out in locale time and 24h format."
      example: 30
      default: 0
      selector:
        number:
          min: 0
          max: 59
          step: 1
          mode: slider
    index:
      name: "Index"
      description: "Index is needed when the lawn mower is to keep out of multiple locations at the same time. Different index values per no-go area."
      example: 1
      default: 1
      selector:
        number:
          mode: box
